uploading prob 6and 7
shankar7791/MI-8-systems pull request #23
Opened 2020-09-15 14:03 UTC by humeratamkin

2020-09-17 17:45 UTC, Harshada-github commented on Personel/humera/programs/sept7/prob6.c
> +
remove extra line spaces

2020-10-03 05:53 UTC, PrajwalYadav reviewed
remove extra spaces 
remove comments from code other than name of program

2020-10-05 13:34 UTC, PrajwalYadav reviewed
coding style should arrange properly

2020-10-13 11:55 UTC, AdeshK1331 commented on Team_02/linkstd.c
> +  int main()
main

2020-10-13 11:56 UTC, AdeshK1331 commented on Team_02/linkstd.c
> +{
check the coding style.

2020-10-13 11:57 UTC, AdeshK1331 reviewed
something

2020-10-13 12:00 UTC, AdeshK1331 requested changes
if

2020-10-13 12:01 UTC, AdeshK1331 approved these changes

2020-11-09 03:39 UTC, merged